################################################################
# Global configuration
################################################################
#debug = true
logLevel = "ERROR"

[entryPoints]
    [entryPoints.http]
    address = ":80"

################################################################
# Web configuration backend
################################################################
[web]
address = ":8080"

################################################################
# Docker configuration backend
################################################################
[docker]
domain = "dev"

[file]
watch = true
filename="/etc/traefik/rules/rules.toml"

